name: Docker

on:
  workflow_call: 

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Docker
      run: |
          sudo apt-get update
          sudo apt-get install -y \
              apt-transport-https \
              ca-certificates \
              curl \
              software-properties-common \
              lsb-release \
              gnupg-agent
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Install Docker Compose
      run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

    - name: setup docker build
      uses: docker/setup-buildx-action@v3.7.1

  #  - name: Download a Build Artifact
   #   uses: actions/download-artifact@v4.1.8
    #  with:
   #     name: "programa"

          

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: janazi1
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}


    - name: Build and push Docker images
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: janazi1/go_ci:v1
          
